FROM ubuntu

MAINTAINER Ritesh "rithu.ritesh@gmail.com"

# Update aptitude with new repo
RUN apt-get update

# install defaults
RUN apt-get install -y python
RUN apt-get install -y python-pip
RUN apt-get install -y git
RUN pip install flask

RUN git clone https://github.com/Ritesh007/webservice.git

EXPOSE 5000
CMD ["python", "webservice/webapp_flask/webapp/webapp.py"]
